server:
    port: 9610

spring:
  data:
    mongodb:
      host: 10.45.250.101
      port: 9017
      database: user_db
      username: user_db_usr

app:
  changelog: ru.techlab.mock.samples.reset.password.changelogs
  pdffile: "files/forma-2-ndfl.pdf"

logging:
  level:
    org.springframework.data: debug