server:
    port: 9610

spring:
  data:
    mongodb:
      host: 10.45.250.101
      port: 9017
      database: blog_db
      username: blog_db_usr

logging:
  level:
    org.springframework.data: debug